name: Relay Compiler Binary

on:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Test
        working-directory: compiler
        run:
          cargo test --target x86_64-pc-windows-gnu

      - name: Build
        working-directory: compiler
        run:
          cargo build --all --release --target x86_64-pc-windows-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

